version: '3.8'

services:
  app:
    build: .
    deploy:
      replicas: 4
      # update_config:
      #   delay: 10s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"  # Cambia `localhost` por dominio o IP
      - "traefik.http.services.app.loadbalancer.server.port=8000"
    networks:
      - monitoring
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: services
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monitoring

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - monitoring

  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"  # Habilita el dashboard de Traefik 
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--tracing.jaeger=true"
      - "--tracing.jaeger.samplingServerURL=http://jaeger:5778/sampling"
      - "--tracing.jaeger.localAgentHostPort=jaeger:6831"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard de Traefik 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - monitoring

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    networks:
      - monitoring

networks:
  monitoring:

volumes:
  portainer_data:
